### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by ppyt** [ralphcajipe/chatgpt-prompt-engineering#1]
ModuleNotFoundError: No module named 'dotenv'

should i using “pip install dotenv”?

**Comment by ralphcajipe** [comment]
Yes, you should use `pip install python-dotenv` to install the `dotenv` module. The error message you are seeing is because the module is not installed in your system¹²³.

Source: Conversation with Bing, 5/8/2023
(1) Modulenotfounderror: no module named dotenv ( Solved ). https://www.datasciencelearner.com/modulenotfounderror-no-module-named-dotenv-solved/.
(2) ModuleNotFoundError: No module named 'dotenv' in Python. https://bobbyhadz.com/blog/python-no-module-named-dotenv.
(3) How to Fix ModuleNotFoundError: no module named ‘dotenv’. https://appdividend.com/2022/12/26/modulenotfounderror-no-module-named-dotenv/.
(4) import - no module named 'dotenv' python 3.8 - Stack Overflow. https://stackoverflow.com/questions/59572174/no-module-named-dotenv-python-3-8.
(5) PYTHON-DOTENV ERROR: no module named 'dotenv' - Stack Overflow. https://stackoverflow.com/questions/62744848/python-dotenv-error-no-module-named-dotenv.
(6) [Fixed] ModuleNotFoundError: No Module Named Dotenv. https://www.pythonpool.com/fixed-modulenotfounderror-no-module-named-dotenv/.
